name: 'CloudFormation Template Generator'
description: 'Generates CloudFormation template for MATLAB on AWS'

inputs:
  ami_map:
    description: 'JSON string mapping regions to AMI IDs'
    required: true
  matlab_release:
    description: 'MATLAB release version'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Generate Template
      shell: bash
      run: |
        python ${{ github.action_path }}/generate.py \
          --ami-map '${{ inputs.ami_map }}' \
          --release ${{ inputs.matlab_release }} \
