name: Build and test MATLAB on AWS

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      matlab_release:
        description: 'MATLAB Release Version'
        required: true
        default: 'R2024b'

env:
  AWS_REGION: us-east-1
  TARGET_REGIONS: >-
    us-east-1,us-east-2,us-west-1,us-west-2,ca-central-1,
    eu-central-1,eu-west-1,eu-west-2,eu-west-3,eu-north-1,
    sa-east-1,me-south-1,ap-east-1,ap-south-1,ap-northeast-1,
    ap-northeast-2,ap-southeast-1,ap-southeast-2

jobs:
  build:
    name: Build and test MATLAB on AWS
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      # Skip for now, will implement this later
      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
      #     aws-region: ${{ env.AWS_REGION }}

      - name: Build MATLAB AMI
        id: build
        run: |
          # Placeholder for Packer build step
          # This will be implemented later with actual Packer configuration
          echo "ami_id=ami-1234567890abcdef0" >> $GITHUB_OUTPUT

      - name: Copy AMI to Regions
        id: copy-ami
        uses: ./.github/actions/copy-ami
        with:
          source_ami_id: ${{ steps.build.outputs.ami_id }}
          source_region: ${{ env.AWS_REGION }}
          target_regions: ${{ env.TARGET_REGIONS }}

      - name: Generate CloudFormation Template
        uses: ./.github/actions/template-gen
        with:
          ami_map: '{"us-east-1": {"AMI": "${{ steps.build.outputs.ami_id }}"}}'
          matlab_release: ${{ github.event.inputs.matlab_release || 'R2024b' }}
  
  test:
    steps:
      - name: Run Certification Tests
        uses: ./.github/actions/test-runner
        with:
          template_file: template/matlab-aws.json
          ami_id: ${{ steps.build.outputs.ami_id }}
          aws_region: ${{ env.AWS_REGION }}
          vpc_id: ${{ secrets.TEST_VPC_ID }}
          subnet_id: ${{ secrets.TEST_SUBNET_ID }}
          key_name: ${{ secrets.TEST_KEY_NAME }}
          client_ip: ${{ secrets.TEST_CLIENT_IP }}
          test_password: ${{ secrets.TEST_PASSWORD }}
  
  publish:
    steps:
      - name: Create Release
        id: create_release
        if: success()
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.matlab_release || 'R2024a' }}
          release_name: MATLAB ${{ github.event.inputs.matlab_release || 'R2024a' }}
          body: |
            MATLAB on AWS CloudFormation Template Release

            This release includes:
            - Updated AMI mappings for all supported regions
            - Certified and tested template
            - Improved security configurations

            For full documentation, please visit the repository README.
          draft: false
          prerelease: false

      - name: Upload Template Asset
        if: success()
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: template/matlab-aws.json
          asset_name: aws-matlab-template.json
          asset_content_type: application/json